name: Triển khai Docusaurus lên GitHub Pages

on:
  push:
    branches:
      - main  # Triển khai khi có thay đổi trên nhánh 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v3

      - name: Thiết lập Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Cài đặt phụ thuộc
        run: yarn install

      - name: Build trang web
        run: yarn build

      - name: Triển khai lên GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
